# Generated by Django 2.1.7 on 2019-12-06 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20191205_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlog',
            name='personId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pages.Person'),
        ),
    ]
