# Generated by Django 2.1.7 on 2019-12-06 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191205_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlog',
            name='timeIn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='personlog',
            name='timeOut',
            field=models.DateTimeField(null=True),
        ),
    ]
