# Generated by Django 2.1.7 on 2019-12-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20191206_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlog',
            name='timeIn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
