# Generated by Django 2.1.7 on 2019-12-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20191207_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='bk_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bk_PersonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personId', models.IntegerField()),
                ('timeIn', models.DateTimeField(auto_now=True, null=True)),
                ('timeOut', models.DateTimeField(null=True)),
            ],
        ),
    ]
