# Generated by Django 2.1.7 on 2019-12-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_bk_person_bk_personlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bk_Person',
        ),
        migrations.DeleteModel(
            name='bk_PersonLog',
        ),
    ]
