# Generated by Django 3.0 on 2019-12-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20191207_2235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
